remote_theme: pages-themes/minimal@v0.2.0
plugins:

- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Hi there, Iâ€™m John (Juan).
description: ğŸš€ As a Marketing Technology Specialist, I'm all about maximizing your brand's reach with tech-savvy strategies.

Proficient in leveraging data-driven insights and platform optimization

Catch me brainstorming marketing strategies or diving into consumer insights â€“ I'm a tech enthusiast with a marketing twist.

Just as I analyze data, I devour knowledge. Currently, I'm loving to read insights that fuel my marketing creativity.

I'm a firm believer in Effective Altruism for marketing. Let's build campaigns that don't just sell but also resonate, contribute, and create a positive impact â€“ no harm, just growth!

Ready to blend the power of tech ğŸŒ with compelling marketing? Let's make your brand shine!


