title: Hi there ðŸ‘‹ Iâ€™m John (Juan).
logo: https://upload.wikimedia.org/wikipedia/commons/b/bf/Duvor.gif 
description: As a Marketing Technology Specialist I'm all about maximizing your brand's reach with tech-savvy strategies. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
