remote_theme: pages-themes/minimal@v0.2.0
plugins:

- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [ğŸ‘‹ Hi there Iâ€™m John (Juan)]
description: [ğŸš€ As a Marketing Technology Specialist, I'm all about maximizing your brand's reach with tech-savvy strategies. ğŸ“Š Proficient in leveraging data-driven insights and platform optimization. ğŸ’¡ Catch me brainstorming marketing strategies or diving into consumer insights ğŸ“š Just as I analyze data, I devour knowledge ğŸ¤ I'm a firm believer in Effective Altruism for marketing Ready to blend the power of tech ğŸŒ with compelling marketing? Let's make your brand shine!]

